from . import campus_process
from . import campus_process_permission
from . import campus_evaluation_version
from . import campus_criterion
from . import campus_criterion_scale
from . import campus_subject
from . import campus_interview_slot
from . import campus_scoring_engine
from . import campus_application_score
from . import campus_application_subject
from . import campus_submission
from . import campus_course_breakdown
from . import campus_shooting_program
from . import campus_shooting_session
from . import hr_applicant
