from . import (
    campus_application_score,
    campus_application_subject,
    campus_course_breakdown,
    campus_criterion,
    campus_criterion_scale,
    campus_evaluation_version,
    campus_interview_slot,
    campus_process,
    campus_process_permission,
    campus_scoring_engine,
    campus_shooting_program,
    campus_shooting_session,
    campus_subject,
    campus_submission,
    hr_applicant,
)
