import json

from odoo import _, api, fields, models


class CampusSubmission(models.Model):
    """The raw payload exactly as the web form sent it.

    Written before anything is parsed, so a mapping bug can never lose an
    application: fix the criterion's source field, hit Re-process, and the
    candidate is recreated from the original bytes rather than chased for a
    resubmission. Also the audit trail for who submitted what and when.
    """

    _name = 'campus.submission'
    _description = 'Campus+ Raw Submission'
    _order = 'create_date desc, id desc'
    _rec_name = 'reference'

    reference = fields.Char("Reference", required=True, index=True, copy=False)
    external_ref = fields.Char(
        "External Reference", index=True, copy=False,
        help="Idempotency key generated by the web form. A retry carrying a "
             "reference we have already seen returns the original record instead "
             "of creating a duplicate.")
    payload = fields.Json("Payload", help="The request body as received.")
    payload_preview = fields.Text("Payload (readable)", compute='_compute_payload_preview')

    state = fields.Selection([
        ('received', 'Received'),
        ('processed', 'Processed'),
        ('rejected', 'Rejected'),
        ('duplicate', 'Duplicate'),
    ], string="Status", default='received', required=True, index=True)
    error_code = fields.Char("Error Code", readonly=True)
    error_message = fields.Text("Error", readonly=True)

    applicant_id = fields.Many2one(
        'hr.applicant', "Application", ondelete='set null', index='btree_not_null')
    version_id = fields.Many2one(
        'campus.evaluation.version', "Evaluation Version", ondelete='set null')

    source_ip = fields.Char("Source IP", index=True, readonly=True)
    origin = fields.Char("Origin", readonly=True)
    user_agent = fields.Char("User Agent", readonly=True)
    email = fields.Char("Email", index=True, readonly=True)

    _reference_uniq = models.Constraint(
        'unique(reference)',
        'Submission references must be unique.',
    )

    @api.depends('payload')
    def _compute_payload_preview(self):
        for submission in self:
            if not submission.payload:
                submission.payload_preview = ''
                continue
            try:
                submission.payload_preview = json.dumps(
                    submission.payload, indent=2, ensure_ascii=False, sort_keys=True)
            except (TypeError, ValueError):
                submission.payload_preview = str(submission.payload)

    @api.model
    def _next_reference(self):
        return self.env['ir.sequence'].next_by_code('campus.submission') or \
            fields.Datetime.now().strftime('SUB/%Y%m%d/%H%M%S%f')

    def action_reprocess(self):
        """Rebuild the application from the stored payload.

        Used after correcting a criterion's source field: no candidate has to
        resubmit for the fix to reach historical rows.
        """
        Applicant = self.env['hr.applicant']
        for submission in self:
            if not submission.payload:
                continue
            applicant = Applicant._campus_apply_payload(
                submission.payload, applicant=submission.applicant_id)
            submission.write({
                'applicant_id': applicant.id,
                'state': 'processed',
                'error_code': False,
                'error_message': False,
            })
            applicant.action_campus_evaluate()
        return True

    def action_view_applicant(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _("Application"),
            'res_model': 'hr.applicant',
            'res_id': self.applicant_id.id,
            'view_mode': 'form',
        }
