from . import campus_process
from . import academic_person
from . import academic_faculty
from . import academic_period
from . import insite_recruitment_need
from . import academic_engagement
from . import insite_candidature
from . import insite_submission
from . import insite_contract
from . import insite_module_sheet
